---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-code-engine
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/src2img/ce-argocd.git
    targetRevision: main
    path: sample-app

    kustomize: {}

  destination:
    name: sascha-br-sao
    namespace: 1rse18tw4qis
